# Generated by Django 5.2.2 on 2025-06-06 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age_group', models.CharField(choices=[('0-3months', '0-3개월'), ('3-6months', '3-6개월'), ('6-9months', '6-9개월'), ('9-12months', '9-12개월'), ('12-18months', '12-18개월'), ('18-24months', '18-24개월'), ('24-36months', '24-36개월'), ('36-48months', '36-48개월'), ('48-60months', '48-60개월'), ('60months+', '60개월 이상')], max_length=50, verbose_name='연령 그룹')),
                ('development_area', models.CharField(choices=[('physical', '신체 발달'), ('cognitive', '인지 발달'), ('language', '언어 발달'), ('social', '사회성 발달'), ('emotional', '정서 발달'), ('self_care', '자조 기능')], max_length=50, verbose_name='발달 영역')),
                ('title', models.CharField(max_length=200, verbose_name='이정표 제목')),
                ('description', models.TextField(verbose_name='이정표 설명')),
                ('order', models.IntegerField(default=0, verbose_name='표시 순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '발달 이정표',
                'verbose_name_plural': '발달 이정표들',
                'db_table': 'development_milestones',
                'ordering': ['age_group', 'development_area', 'order'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='기록 날짜')),
                ('age_group', models.CharField(choices=[('0-3months', '0-3개월'), ('3-6months', '3-6개월'), ('6-9months', '6-9개월'), ('9-12months', '9-12개월'), ('12-18months', '12-18개월'), ('18-24months', '18-24개월'), ('24-36months', '24-36개월'), ('36-48months', '36-48개월'), ('48-60months', '48-60개월'), ('60months+', '60개월 이상')], max_length=50, verbose_name='연령 그룹')),
                ('development_area', models.CharField(blank=True, choices=[('physical', '신체 발달'), ('cognitive', '인지 발달'), ('language', '언어 발달'), ('social', '사회성 발달'), ('emotional', '정서 발달'), ('self_care', '자조 기능')], max_length=50, null=True, verbose_name='발달 영역')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('description', models.TextField(verbose_name='상세 내용')),
                ('record_type', models.CharField(choices=[('development_record', '발달 기록'), ('milestone_achievement', '이정표 달성'), ('observation', '관찰 기록'), ('concern', '우려사항')], default='development_record', max_length=50, verbose_name='기록 유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_records', to='api_service.userchild', verbose_name='자녀')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_records', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '발달 기록',
                'verbose_name_plural': '발달 기록들',
                'db_table': 'development_records',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentRecordImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.URLField(verbose_name='이미지 URL')),
                ('order', models.IntegerField(default=0, verbose_name='이미지 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vectordb.developmentrecord', verbose_name='발달 기록')),
            ],
            options={
                'verbose_name': '발달 기록 이미지',
                'verbose_name_plural': '발달 기록 이미지들',
                'db_table': 'development_record_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChildMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('achieved_date', models.DateField(verbose_name='달성 날짜')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='메모')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achieved_milestones', to='api_service.userchild', verbose_name='자녀')),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_achievements', to='vectordb.developmentmilestone', verbose_name='이정표')),
            ],
            options={
                'verbose_name': '자녀 이정표 달성',
                'verbose_name_plural': '자녀 이정표 달성들',
                'db_table': 'child_milestones',
                'unique_together': {('child', 'milestone')},
            },
        ),
        migrations.AddIndex(
            model_name='developmentrecord',
            index=models.Index(fields=['user'], name='development_user_id_18d3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentrecord',
            index=models.Index(fields=['child'], name='development_child_i_25dbb1_idx'),
        ),
        migrations.AddIndex(
            model_name='developmentrecord',
            index=models.Index(fields=['date'], name='development_date_e0df01_idx'),
        ),
    ]
