# Generated by Django 5.2.2 on 2025-06-06 07:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='세션 제목')),
                ('category', models.CharField(choices=[('general', '일반 상담'), ('development', '발달 상담'), ('health', '건강 상담'), ('behavior', '행동 상담'), ('nutrition', '영양 상담'), ('education', '교육 상담'), ('sleep', '수면 상담'), ('emergency', '응급 상담')], max_length=50, verbose_name='상담 카테고리')),
                ('session_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI 세션 토큰')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='총 사용 토큰 수')),
                ('status', models.CharField(choices=[('active', '활성'), ('completed', '완료'), ('expired', '만료')], default='active', max_length=20, verbose_name='상태')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='마지막 메시지 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='삭제 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '채팅 세션',
                'verbose_name_plural': '채팅 세션들',
                'db_table': 'chat_sessions',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '어시스턴트'), ('system', '시스템')], max_length=20, verbose_name='역할')),
                ('content', models.TextField(verbose_name='메시지 내용')),
                ('tokens', models.IntegerField(default=0, verbose_name='메시지 토큰 수')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='추가 메타데이터')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.chatsession', verbose_name='세션')),
            ],
            options={
                'verbose_name': '채팅 메시지',
                'verbose_name_plural': '채팅 메시지들',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['user'], name='chat_sessio_user_id_54b88f_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['status'], name='chat_sessio_status_f6889c_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session'], name='chat_messag_session_70d2c0_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['created_at'], name='chat_messag_created_eb4133_idx'),
        ),
    ]
